version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  chromatic-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run chromatic

workflows:
  run-unit-tests:
    jobs:
      - build-and-test:
        filters:
          branches:
            - development
            - main
  publish-chromatic:
    jobs:
      - chromatic-deploy:
        filters:
          branches:
            only: development
